website:
  title: "E. IACCARINO"   # short to avoid truncation
  site-url: https://emanueleiacca.github.io/
  favicon: images/logo.jpg
  navbar:
    title: E. IACCARINO
    logo: images/logo.jpg
    logo-alt: "Emanuele Iaccarino personal mark"
    right:
      - href: index.qmd
        text: HOME
      - href: about.qmd
        text: ABOUT
      - href: academic/index.qmd
        text: ACADEMIC
      - href: projects.qmd
        text: PROJECTS
      - href: publications.qmd    # if the page is actually spelled this way keep it; otherwise rename the file and use publications.qmd
        text: PUBLICATIONS
      - href: awards-certifications.qmd
        text: AWARDS & CERTS
      - href: cv.qmd
        text: CV
      - text: CONTACT
        menu:
          - icon: linkedin
            text: LINKEDIN
            href: https://www.linkedin.com/in/emanuele-iaccarino-a4298b27b/
            target: _blank
          - icon: envelope
            text: EMAIL
            href: mailto:emanueleiaccarino.ei@gmail.com
      - icon: github
        href: https://github.com/emanueleiacca
        target: _blank
